<!doctype html>
<html lang="ru">
<head>
    <meta charset="UTF-8">
    <title>Totwit</title>
    <style>
        .container {
            text-align: center;
            color: #333333;
        }
        .content p {
            background-color: rgb(204, 238, 238);
            border-radius: 3px;
            padding: 5px;
        }
        .content span {
            background-color: rgb(238, 238, 238);
            border-radius: 3px;
            padding: 5px;
        }
        .content {
            width: 60%;
            margin:auto;
            text-align: center;
        }
    </style>
</head>
<body>
<div class="container">
    <h2>RSS to Twitter sender:</h2>
    <div class="content">
    <?php if(!empty($sended)):?>
	    <?php
	    foreach($result as $twit) {
	        echo "<p>".$twit["tweet"]."</p>";
	    }
	    ?>    
    <?php endif;?>
    <span>Всего твитов отправлено: <?php echo $sended; ?></span>
    </div>
</div>
</body>
</html>